[DOC_MODEL]
required: output_path,path_cdom,file_cdom,path_sst,file_sst,path_mld,file_mld,path_chl,file_chl,path_class,file_class
output_path: output_path, None
output_file: str,doc_$DATE$.nc
path_cdom: input_path,None
file_cdom: str,None
path_sst: input_path,None
file_sst: str,None
path_mld: input_path,None
file_mld: str,None
path_chl: input_path,None
file_chl: str,None
path_class: input_path,None
file_class: str,None
path_ref: input_path,None
file_ref: str, None
variable_ref: str,None
format_file_cdom: str,%%Y%%j
format_file_sst: str,%%Y%%j
format_file_mld: str,%%Y%%j
format_file_chl: str,%%Y%%j
format_file_class: str,%%Y%%j
format_file_ref: str, %%Y%%j
create_empty_if_not_datasets: boolean, False

[CDOM_COMPOSITE]
required: input_path,list_files,list_var,output_path,output_file
input_type: str,rrs,"rrs,cdom_daily"
input_path: input_path,None
list_files: strlist,None
list_files_format: strlist,"%%Y%%j"
list_var: strlist,None
output_path: output_path,None
output_file: str,None
resampler: strlist,None
type_resampler: str,file_ref
download: str, None
n_days: int, 8
dates_0w: intlist, 0
dates_1w: intlist, -8
dates_2w: intlist, -16
#processing_by_date: boolean, True
input_path_cdom: input_path, None
input_path_cdom_organization: str, "%%Y/%%j"
file_cdom: str, None
file_cdom_format: str, "%%Y%%j"
var_cdom: str, "Acdom_sat"

[SST_COMPOSITE]
required: input_path,list_files,list_var,output_path,output_file
input_path: input_path,None
list_files: strlist,None
list_files_format: strlist,"%%Y%%j"
list_var: strlist, None
output_path: output_path, None
output_file: str, None
resampler: strlist, None
download: str, None
type_resampler: str,file_ref
resampler_shift_lat: int, None
resampler_shift_lon: int, None
n_days: int, 8
dates_0w: intlist, 0
dates_1w: intlist, -8
dates_2w: intlist, -16


[MLD_COMPOSITE]
required: input_path,list_files,list_var,output_path,output_file
input_path: input_path,None
list_files: strlist,None
list_files_format: strlist,"%%Y%%j"
list_var: strlist, None
output_path: output_path, None
output_file: str, None
resampler: strlist, None
type_resampler: str,file_ref
resampler_shift_lat: int, None
resampler_shift_lon: int, None
download: str, None
n_days: int, 8
dates_0w: intlist, 0
dates_1w: intlist, -8
dates_2w: intlist, -16

[CHL_COMPOSITE]
required: input_path,list_files,list_var,output_path,output_file
input_path: input_path,None
list_files: strlist,None
list_files_format: strlist,"%%Y%%j"
list_var: strlist, None
output_path: output_path, None
output_file: str, None
resampler: strlist, None
type_resampler: str,file_ref
download: str, None
n_days: int, 8
dates_0w: intlist, 0
dates_1w: intlist, -8
dates_2w: intlist, -16

[CLASS_COMPOSITE]
required: input_path,list_files,list_var,output_path,output_file
input_type: str,rrs,"rrs,class_daily"
input_path: input_path,None
list_files: strlist,None
list_files_format: strlist,"%%Y%%j"
list_var: strlist, None
output_path: output_path, None
output_file: str, None
resampler: strlist, None
type_resampler: str,file_ref
download: str, None
n_days: int, 8
dates_0w: intlist, 0
dates_1w: intlist, -8
dates_2w: intlist, -16
input_path_class: input_path, None
input_path_class_organization: str, "%%Y/%%j"
file_class: str, None
file_class_format: str, "%%Y%%j"
var_class: strlist, "Class,Probability"
composite_class: str, mode_avg, "mode_avg,prob_avg" 

[DOWNLOAD]
required: type
type: str,CMEMS,"CMEMS"
product: str,None
dataset: str,None
bucket: str,None
tag: str,None
endpoint:str,https://s3.waw3-1.cloudferro.com
remote_name_abs:str,None
output_path: output_path, None
output_path_structure: str,%%Y/%%j
output_file: str, None
output_file_format: str, %%Y%%m%%d


